spring.application.name=GreenU
server.port=8080
spring.main.banner-mode=off

#Adds color annotation
spring.output.ansi.enabled=always

#Database configuration
spring.sql.init.mode=always

#MySQL configuration
spring.datasource.url=jdbc:mysql://localhost:3306/GreenUnderground
spring.datasource.username=root
spring.datasource.password=robinson
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Hibernate configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true

