INSERT INTO Galleries(id, name, address, image_Url, founder, location, url) VALUES
(1, 'Richard Beavers Gallery', '14 Wooster Street', 'www.richardbeaversgallery.com', 'Richard Beavers', 'Manhattan', 'www.richardbeaversgallery.com'),
(2, 'MoCADA', '80 Hanson Pl','www.MoCada.com','Laurie Angela Cumbo', 'Brooklyn','www.MoCada.com'),
(3, 'Bedford Stuyvesant Museum of African Art', '1157 Bedford Ave', 'www.bsma.com','Eric Edwards', 'Brooklyn', 'www.bsma.com'),
(4, 'Bishop Gallery', '630 Flushing Ave', 'www.bishopgallery.com', 'Erwin John & Stevenson Dunn Jr.', 'Brooklyn', 'www.bishopgallery.com'),
(5, 'The Studio Museum', '429 West 127th St', 'www.studiomuseum.com', 'Charles Inniss','Manhattan', 'www.studiomuseum.com'),
(6, 'Nicola Vassell Gallery', '138 10th Avenue', 'www.vassellgallery.com','Nicola Vassell', 'Brooklyn','www.vassellgallery.com'),
(7, 'Heath Gallery', '24 W 120th St','www.heathgallery.com', 'Thomas Edwin & Saundra Alexis Heath', 'Manhattan', 'www.heathgallery.com'),
(8, 'Long Gallery', '2073 Adam Clayton Powell Jr Blvd', 'www.longgallery.com', 'Lewis Long', 'Manhattan','www.longgallery'),
(9, 'Hannah Traore Gallery', '150 Orchard Street', 'www.hannahtraoregallery.com', 'Hannah Traore', 'Manhattan','www.hannahtraoregallery'),
(10, 'Welancora Gallery', '33 Herkimer Street', 'www.welancoragallery.com','Ivy N. Jones', 'Brooklyn', 'www.welancoragallery.com'),
(11, 'Dorsey Art Gallery', '553 Rogers Ave.','www.dorseyartgallery.com','Lawrence P. Dorsey', 'Brooklyn','www.dorseyartgallery.com'),
(12, 'Ground Gallery', '80 Richards St.', 'www.groundgallery.com','Krista Scenna & Jill Benson', 'Brooklyn', 'www.groundgallery.com'),
(13, 'Medium Tings', '1134 President Street', 'www.mediumtings.com', 'Stephanie Baptist','Brooklyn', 'www.mediumtings.com'),
(14, 'Jenkins Johnson Gallery', '207 Ocean Ave.', 'www.jenkinsjohnsongallery.com', 'Karen Jenkins Johnson','Brooklyn', 'www.jenkinsjohnsongallery.com'),
(15, 'Housing Gallery', '191 Henry St.', 'www.housinggallery.com', 'KJ Freeman & Eileen Skyers','Manhattan','www.housinggallery.com'),
(16, 'Essie Green Gallery', '4213,419 Convent Ave. A','www.essiegreengallery.com','Essie Green & Sherman Edmiston', 'Manhattan', 'www.essiegreengallery.com'),
(17, 'Black Gotham Experience', '192 Front St.', 'www.blackgotham.com', 'Kamau Ware', 'Manhattan','www.blackgotham.com'),
(18, 'Cindy Rucker Gallery', '143 Orchard Street', 'www.cindyruckergallery.com', 'Cindy Rucker', 'Manhattan','www.cindyruckergallery.com'),
(19, 'Peg Alston Fine Arts', '407 Central Park W Apt. K', 'www.pegalstonfinearts.com', 'Peg Alston', 'Manhattan', 'www.pegalstonfinearts.com'),
(20, 'Skoto Gallery', '529 W20th St., #5FL','www.skotogallery.com', 'Skoto Aghahowa', 'Brooklyn','www.skotogallery.com'),
(21, 'Mackey Twins Art Gallery', '457 E. Sidney Ave.', 'www.mackeytwinsartgallery.com', 'Karen & Sharon Mackey', 'Brooklyn', 'www.mackeytwinsartgallery.com'),
(22, 'June Kelly Gallery', '166 Mercer St. #3C', 'www.junekellygallery.com', 'June Kelly', 'Brooklyn', 'www.junekellygallery.com'),
(23, 'The Compound', '185 Van Dyke St.', 'www.compound7.series', 'Free Richardson', 'Manhattan', 'www.compound7.series'),
(24, 'Cierra Britton Gallery', '220b Plymouth St.', 'www.cierrabritton.com', 'Cierra Britton', 'Brooklyn','www.cierrabritton.com'),
(25, 'Black Wall Street Gallery', '14 Wooster St.','www.bwsgallery.com', 'Ricco Wright', 'Manhattan', 'www.bwsgaler.com'),
(26, 'Tanya Weddemire Gallery', '254 36th Street, STE C257', 'www.tanyaweddemiregallery.org', 'Tanya Weddemire', 'Manhattan','www.tanyaweddemiregallery.org'),
(27, 'Calabar Gallery', '306 W 38th St.', 'www.calabargallery.com', 'Atim Annette Oton', 'Manhattan','www.calabargallery.com'),
(28, 'Bill Hodges Gallery', '521 W 20th St., #10E','www.billhodgesgallery.com', 'Bill Hodges', 'Manhattan', 'www.billhodgesgallery.com'),
(29, 'Curtiss Jacobs Gallery', '2075 Adam Clayton Powell Jr Blvd', 'www.curtissjacobsgallery.com', 'Curtiss Jacobs', 'Manhattan','www.curtissjacobsgallery.com'),
(30, 'Kente Royal Gallery', '2373 Adam Clayton Powell Jr Blvd', 'www.kenteroyalgallery.com', 'Phyllis & Dodji Gbedemah', 'Manhattan','www.kenteroyalgallery.com');

INSERT INTO Cafes(id, name, address, location, image_Url, beverage, url) VALUES
(1, 'Che', '302 Malcolm X Blvd.', 'Manhattan', 'www.che.com', 'Cafe', 'www.che.com'),
(2, 'I Like It Black', '409 W 125th St.', 'Manhattan', 'www.ilikeitblack', 'Cafe', 'www.ilikeitblack'),
(3, 'Buuni Cafe', '213 Pinehurst Ave.', 'Manhattan', 'www.buunicafe.com', 'Cafe', 'www.buunicafe.com'),
(4, 'Hibiscus Brew', '546 Flatbush Ave.','Brooklyn', 'www.hibiscusbrew.com', 'Cafe', 'www.hibiscusbrew.com'),
(5, 'Aunts Et Uncles', '1407 Nostrand Ave.', 'Brooklyn', 'www.auntsetuncles.com', 'Cafe', 'www.auntsetuncles.com'),
(6, 'Bklyn Blend', '194 Tompkins Ave.', 'Brooklyn', 'www.blklynblend.com', 'Cafe', 'www.blklynblend.com'),
(7, 'Bushwick Grind', '63 Whipple St.', 'Brooklyn', 'www.bushwickgrind.com', 'Cafe', 'www.bushwickgrind.com'),
(8, 'Brown Butter Craft Bar & Kitchen', '413 Thompkins Ave.', 'Brooklyn', 'www.brownbutternyc.com', 'Cafe', 'www.brownbutternyc.com'),
(9, 'St. Michel Cafe', '462 Irving Ave.', 'Brooklyn', 'www.michelcafe.com', 'Cafe', 'www.michelcafe.com'),
(10, 'Milk & Pull', '778 Seneca Ave.', 'Brooklyn', 'www.milkandpull.com', 'Cafe', 'www.milkandpull.com'),
(11, 'Lakou Cafe', '195 Utica Ave.', 'Brooklyn', 'www.lakoucafe.com', 'Cafe', 'www.lakoucafe.com'),
(12, 'Sweet Sundays Cafe', '2916 Beverley Rd.', 'Brooklyn', 'www.sweetsunday.com', 'Cafe','www.sweetsunday.com'),
(13, 'Boogie Down Grind', '88 Hunts Point', 'Bronx', 'www.boogiedowngrind.com', 'Cafe', 'www.che.com'),
(14, 'Ginjan Cafe', '85 E 125th St.', 'Manhattan', 'www.ilikeitblack', 'Cafe', 'www.ilikeitblack'),
(15, 'The Oma, Shop', '1707 Amsterdam Ave.', 'Manhattan', 'www.buunicafe.com', 'Cafe', 'www.buunicafe.com'),
(16, 'LoveLane BK', '674 Nostrand Ave.', 'Brooklyn', 'www.hibiscusbrew.com', 'Cafe', 'www.hibiscusbrew.com'),
(17, 'Coffee Uplifts People', '329 Gates Ave.', 'Brooklyn', 'www.auntsetuncles.com', 'Cafe', 'www.auntsetuncles.com'),
(18, 'Chez Alex', '72 Ralph Ave.',  'Brooklyn', 'www.blklynblend.com', 'Cafe', 'www.blklynblend.com'),
(19, 'Zaca Cafe', '429 Marcus Garvey Blvd.', 'Brooklyn', 'www.bushwickgrind.com', 'Cafe', 'www.bushwickgrind.com'),
(20, 'Greenhouse Cafe @ Seed Brklyn', '1217 Bedford Ave.', 'Brooklyn', 'www.brownbutternyc.com', 'Cafe', 'www.brownbutternyc.com'),
(21, 'Brooklyn Perk', '605 Flatbush Ave.', 'Brooklyn', 'www.michelcafe.com', 'Cafe', 'www.michelcafe.com'),
(22, 'NBHD Brulee', '2620 Frederick Douglass Blvd.', 'Manhattan', 'www.milkandpull.com', 'Cafe', 'www.milkandpull.com'),
(23, 'Nurish', '637A Vanderbilt Ave.', 'Brooklyn', 'www.lakoucafe.com', 'Cafe', 'www.lakoucafe.com'),
(24, 'Deja Brew Cafe', '102- 10 Jamaica Ave.', 'Queens', 'www.sweetsunday.com', 'Cafe','www.sweetsunday.com'),
(25, 'Lips Cafe', '1412 Nostrand Ave.', 'Brooklyn', 'www.che.com', 'Cafe', 'www.che.com'),
(26, 'September', '83 Saratoga Ave.', 'Brooklyn', 'www.ilikeitblack', 'Cafe', 'www.ilikeitblack'),
(27, 'Cups and Books', '2024 Bedford Ave.', 'Brooklyn', 'www.buunicafe.com', 'Cafe', 'www.buunicafe.com'),
(28, 'Miss Barbs', '1038 Nostrand Ave.', 'Brooklyn', 'www.hibiscusbrew.com', 'Cafe', 'www.hibiscusbrew.com'),
(29, 'Brooklyn Tea', '411 Lewis Ave.', 'Brooklyn', 'www.auntsetuncles.com', 'Cafe', 'www.auntsetuncles.com'),
(30, 'Cafe Lakay', '3323 Avenue I',  'Brooklyn', 'www.blklynblend.com', 'Cafe', 'www.blklynblend.com');

INSERT INTO JuiceBars(id, name, address, location, image_Url, beverage, url) VALUES
(1, 'Bkln Blend', '194 Tompkins Ave', 'Brooklyn', 'www.blklynblend.com', 'Juice Bar', 'www.blklynblend.com'),
(2, 'The Juice Gallery', '1647 Bedford Ave.', 'Brooklyn', '', 'Juice Bar', ''),
(3, 'Passa Passa', '401 Rogers Ave.', 'Brooklyn', '', 'Juice Bar', ''),
(4, 'Unks Place', '1962 Madison Ave.', 'Manhattan', '', 'Juice Bar', ''),
(5, 'Juice Worx', '90 St. Nicholas', 'Manhattan', '', 'Juice Bar', ''),
(6, 'Cocoa Bean Juice & Salad Bar', '1510 Nostrand Ave.', 'Brooklyn', '', 'Juice Bar', ''),
(7, 'Canarsie Blend Juice Bar', '9202 Avenue M', 'Brooklyn', '', 'Juice Bar', ''),
(8, 'Mad Juicy', '100 W 139th St.', 'Manhattan', '', 'Juice Bar', ''),
(9, 'Juice Joint', '144-14 ROckaway Blvd.', 'Queens', '', 'Juice Bar', ''),
(10, 'Les Deux Nutrition Juice', '662 Blake Ave.', 'Brooklyn', '', 'Juice Bar', ''),
(11, 'Uptown Juice Bar', '2524 Adam Clayton Powell Jr. Blvd.', 'Manhattan', '', 'Juice Bar', ''),
(12, 'Green Garden Health Food', '3543 White Plains Rd.', 'Bronx', '', 'Juice Bar', ''),
(13, 'The Bush Doctor Juice Bar', '307 Tompkins Ave.', 'Brooklyn','', 'Juice Bar', ''),
(14, 'Secret Garden Juice Bar & Tea House', '347 Lewis Ave.', 'Brooklyn', '', 'Juice Bar', ''),
(15, 'The Nourish Bar', '107-05 Guy R Brewer Blvd', 'Queens', '', 'Juice Bar', ''),
(16, 'Mother Earth Juice Bar & Health Food Cafe', '115-42 Sutphin Blvd.', 'Queens', '', 'Juice Bar', ''),
(17, 'Veggies Natural Juice Bar', '85 Franklin Ave.', 'Brooklyn', '', 'Juice Bar', ''),
(18, 'Bar Got Juice', '204-11 Hollis Ave.', 'Queens', '', 'Juice Bar', '');


INSERT INTO Bars(id, name, address, location, image_Url, beverage, url) VALUES
(1, 'Whisk & Whiskey', '289 Fourth Ave.', 'Brooklyn', '', 'Bar', ''),
(2, 'Ashford & Simpsons Sugar Bar', '254 W. 72nd St.', 'Manhattan', '', 'Bar', ''),
(3, 'The Rum Bar', '733 Franklin Ave.', 'Brooklyn', '', 'Bar', ''),
(4, 'Pearl Lees Washtub', '314 Rogers Ave.', 'Brooklyn', '', 'Bar', ''),
(5, 'The Bush', '33 Troutman St.', 'Brooklyn', '', 'Bar', ''),
(6, 'Bar Room @ Dick & Janes', '300 Malcolm X Blvd.', 'Manhattan', '', 'Bar', ''),
(7, 'Las Lap', '74 Orchard St.', 'Manhattan', '', 'Bar', ''),
(8, 'Harlem Hops', '2268 Clayton Powell Jr. Blvd.', 'Manhattan', '', 'Bar', ''),
(9, 'Bed Vyne Brew', '370 Tompkins Ave.', 'Brooklyn', '', 'Bar', ''),
(10, 'The Rogers Garden', '708 Rogers Ave.', 'Brooklyn', '', 'Bar', ''),
(11, 'Bierwax', '556 Vanderbilt Ave.', 'Brooklyn', '', 'Bar', ''),
(12, 'The Se7en', '667 Washington Ave.', 'Brooklyn', '', 'Bar', ''),
(13, 'Filthy Diamond', '679 Knickerbocker Ave.', 'Brooklyn', '', 'Bar', ''),
(14, 'Jimmys Corner', '140 W 44th St.', 'Manhattan', '', 'Bar', ''),
(15, 'The Franklin', '448 Franklin Ave.', 'Brooklyn', '', 'Bar', ''),
(16, 'Deia', '642 Rogers Ave.', 'Brooklyn', '', 'Bar', ''),
(17, 'Charm Bar & Restaurant', '448 Dean St.', 'Brooklyn', '', 'Bar', ''),
(18, 'Luckys Cocktail Lounge', '334 Marcus Garvey Blvd.', 'Brooklyn', '', 'Bar', ''),
(19, 'The Nighthorse', '66 Greenpoint Ave.', 'Brooklyn', '', 'Bar', ''),
(20, 'That Bar', '47 5th Ave.', 'Brooklyn', '', 'Bar', ''),
(21, 'Madelines', '113 Franklin St.', 'Brooklyn', '', 'Bar', ''),
(22, 'Another Country', '10 E. 16th St.', 'Manhattan', '', 'Bar', ''),
(23, 'Essence Bar & Grill', '1662 Atlantic Ave.', 'Brooklyn', '', 'Bar', ''),
(24, 'IV Purpose', '1489 Fulton St.', 'Brooklyn', '', 'Bar', ''),
(25, 'Therapy Wine Bar 2.0', '260 Malcolm X Blvd.', 'Brooklyn', '', 'Bar', ''),
(26, '67 Orange', '83 Saratoga Ave.', 'Manhattan', '', 'Bar', ''),
(27, 'Alibi Lounge', '2376 Adam Clayton Powell Jr Blvd.', 'Manhattan', '', 'Bar', ''),
(28, 'Sweet Brooklyn', '608 Nostrand Ave.', 'Brooklyn', '', 'Bar', ''),
(29, 'Patricks Place', '2835 Frederick Douglass Blvd.', 'Brooklyn', '', 'Bar', ''),
(30, '& Sons Ham Bar', '447 Rogers Ave.', 'Brooklyn', '', 'Bar', '');

INSERT INTO Restaurants(id, name, address, image_Url, cuisine, category, location, url, per_person) VALUES
(1, 'Charles Pan-Fried Chicken', '340 W 145th St.', 'https://www.charlespanfriedchicken.com', 'American', 'Fast Casual', 'Manhattan', 'https://www.charlespanfriedchicken.com', '$10pp'),
(2, 'Pig & Butter', '42 Ave. B', 'https://www.pigandbutter.com', 'American', 'Gastropub', 'Manhattan', 'https://www.pigandbutter.com', '$20pp'),
(3, 'Sylvias', '328 Malcolm X Blvd.', 'https://sylviasrestaurant.com', 'Soul Food', 'Casual Dining', 'Manhattan', 'https://sylviasrestaurant.com', '$30pp'),
(4, 'Tatiana', '10 Lincoln Center Plaza', 'https://www.tatiananyc.com', 'Afro Caribbean', 'Fine Dining', 'Manhattan', 'https://www.tatiananyc.com','$150pp'),
(5, 'Bunna Cafe', '1084 Flushing Ave.', 'https://www.bunnaethiopia.net', 'Ethiopian', 'Casual Dining', 'Brooklyn', 'https://www.bunnaethiopia.net','$20pp'),
(6, 'Cheryls Global Soul', '236 Underhill Avenue', 'https://www.cherylsglobalsoul.com','Soul Food', 'Casual Dining', 'Brooklyn','https://www.cherylsglobalsoul.com', '$20pp'),
(7, 'The Islands', '671 Washington Ave.', 'https://www.theislands.getsauce.com', 'Afro Caribbean', 'Casual Dining', 'Brooklyn', 'https://www.theislands.getsauce.com', '$20pp'),
(8, 'Kokomo', '65 Kent Avenue', 'https://www.kokomonyc.com', 'Afro Caribbean', 'Fine Dining', 'Brooklyn', 'https://www.kokomonyc.com', '$50pp'),
(9, 'MangoSeed', '755 Flatbush Avenue', 'https://www.mangoseedbrooklyn.com', 'Afro Caribbean', 'Casual Dining', 'Brooklyn', 'https://www.mangoseedbrooklyn.com', '$20pp'),
(10, 'Peaches HotHouse', '415 Tompkins Ave.', 'https://www.bcrestaurantgroup.com/location/peaches-hot-house-bed-stuy', 'Soul Food', 'Casual Dining', 'Brooklyn', 'https://www.bcrestaurantgroup.com/location/peaches-hot-house-bed-stuy', '$20pp'),
(11, 'Ras Plant Based', '739 Franklin Avenue', 'https://www.mangoseedbrooklyn.com', 'Ethiopian', 'Fast Casual', 'Brooklyn', "https://www.mangoseedbrooklyn.com", '$20pp'),
(12, 'Scarrs Pizza', '22 Orchard St.', 'https://www.scarrspizza.com', 'Pizza', 'Fast Casual', 'Manhattan', 'https://www.scarrspizza.com','$10pp'),
(13, 'Fieldtrip', '109 Malcolm X Blvd.', 'https://www.fieldtripnyc.com', 'American', 'Fast Casual', 'Manhattan', 'https://www.fieldtripnyc.com', '$10pp'),
(14, 'SoCo BK', '509 Myrtle Ave.', 'https://socobklyn.com', 'Cajun', 'Casual Dining', 'Brooklyn', 'https://socobklyn.com', '$50pp'),
(15, 'Sisters', '900 Fulton St.', 'https://www.sistersbklyn.com', 'New American', 'Casual Dining', 'Brooklyn', 'https://www.sistersbklyn.com', '$30pp'),
(16, 'Ghenet', '348 Douglass St.', 'https://www.ghenet.com', 'Ethiopian', 'Casual Dining', 'Brooklyn', 'https://www.ghenet.com', '$30pp'),
(17, 'Negril BK', '256 5th Ave.', 'https://negrilbk.com', 'Afro Caribbean', 'Casual Dining', 'Brooklyn', 'https://negrilbk.com', '$30pp'),
(18, 'Vinateria', '2211 Frederick Douglas Blvd.', 'https://www.vinaterianyc.com', 'Italian', 'Casual Dining', 'Manhattan', 'https://www.vinaterianyc.com', '$30pp'),
(19, 'Seasoned', '128 2nd Ave.', 'https://www.seasonedvegan.com', 'Vegetarian', 'Fast Casual', 'Manhattan', 'https://www.seasonedvegan.com','$10pp'),
(20, 'Queen of Sheba', '650 Tenth Ave.', 'https://www.shebanyc.com', 'Ethiopian', 'Casual Dining', 'Manhattan','https://www.shebanyc.com', '$20pp'),
(21, 'Brooklyn Chop House', '150 Nassau St.', 'https://www.brooklynchophouse.com', 'Asian', 'Fine Dining', 'Brooklyn', 'https://www.brooklynchophouse.com', '$100pp'),
(22, 'Reverence', '2592 Frederick Douglas Blvd.', 'https://reverence.nyc', 'New American', 'Fine Dining', 'Manhattan','https://reverence.nyc', '$100pp'),
(23, 'Brooklyn Beso', '370 Lewis Ave.', 'https://brooklynbeso.com', 'Latin', 'Casual Dining', 'Brooklyn', 'https://brooklynbeso.com', '$30pp'),
(24, 'Teranga', '1280 5th Ave', 'https://itsteranga.com', 'West African', 'Casual Dining', 'Manhattan', 'https://itsteranga.com' , '$30pp'),
(25, 'Ponty Bistro', '144 West 139th Street', 'https://pontybistroharlem.com', 'West African French', 'Casual Dining', 'Manhattan', 'https://pontybistroharlem.com','$30pp'),
(26, 'Yop City', '2324 Arthur Ave.', 'https://yopcityrestaurantny.com', 'West African', 'Casual Dining', 'Bronx','https://yopcityrestaurantny.com', '$20pp'),
(27, 'Cafe Rue Dix', '1451 Bedford Ave.', 'https://www.ruedixbrooklyn.com', 'Senagalese', 'Casual Dining', 'Brooklyn','https://www.ruedixbrooklyn.com', '$30pp'),
(28, 'Ramen By Ra', '348 Bowery', 'https://www.ramenbyra.com', 'Asian', 'Casual Dining', 'Manhattan', 'https://www.ramenbyra.com', '$20pp'),
(29, 'Metropolis', '251 Fulton St.', 'https://www.metropolisbymarcus.com', 'New American', 'Fine Dining', 'Manhattan','https://www.metropolisbymarcus.com', '$100pp'),
(30, 'Radio Kwara', '291 Greene Ave.', 'https://www.radiokwarabk.com', 'West African','Fine Dining', 'Brooklyn','https://www.radiokwarabk.com', '$100pp'),
(31, 'Sushi Oku', '22 Orchard St.', 'https://www.sushioku.com', 'Asian', 'Fine Dining','Manhattan','https://www.sushioku.com', '$100pp'),
(32, 'SAimer', '338 W 46th', 'https://www.saimernyc.com', 'French Caribbean', 'Fine Dining', 'Manhattan', 'https://www.saimernyc.com','$50pp'),
(33, 'File Gumbo Bar', '275 Church St.', 'https://filenyc.com', 'Cajun', 'Fine Dining', 'Manhattan', 'https://filenyc.com', '$100pp'),
(34, 'BLVD Bistro', '2149 Frederick Douglas Blvd.', 'https://www.boulevardbistrony.com', 'Soul Food', 'Casual Dining', 'Manhattan','https://www.boulevardbistrony.com','$50pp'),
(35, 'Cornbread Brooklyn', '409 Eastern Parkway', 'https://cornbreadsoul.com', 'Soul Food', 'Fast Casual', 'Brooklyn', 'https://cornbreadsoul.com', '$20pp'),
(36, 'dùndú', '140 E 41st', 'https://eatdundu.com', 'West African', 'Fast Casual', 'Manhattan', 'https://eatdundu.com', '$10pp'),
(37, 'Fat Fowl', '445 Albee Square W', 'https://www.thefatfowl.com/', 'Afro Caribbean', 'Fast Casual', 'Brooklyn', 'https://www.thefatfowl.com/', '$10pp'),
(38, 'Fyahbun Creative', '324 E. 48th St.', 'https://www.fyahbuncreative.com', 'Afro Caribbean', 'Fast Casual', 'Manhattan', 'https://www.fyahbuncreative.com', '$10pp'),
(39, 'Cadence', '111 E 7th St.', 'https://www.cadencenewyork.com', 'Soul Food, Vegetarian', 'Fine Dining', 'Manhattan', 'https://www.cadencenewyork.com','$50pp'),
(40, 'The Good Good', '1694 Park Ave.', 'https://www.thegoodgoodnyc.com', 'Afro Caribbean', 'Fine Dining', 'Manhattan', 'https://www.thegoodgoodnyc.com','$50pp'),
(41, 'The Crabby Shack', '613 Franklin Ave.', 'https://thecrabbyshack.com', 'Seafood', 'Fast Casual', 'Brooklyn', 'https://thecrabbyshack.com', '$25pp'),
(42, 'Stellas', '321 9th St.', 'https://stellascaribbean.com', 'Afro Caribbean', 'Casual Dining', 'Brooklyn', 'https://stellascaribbean.com', '$30pp'),
(43, 'Black Forest', '733 Fulton Street', 'https://www.blackforestbrooklyn.com', 'German', 'Casual Dining', 'Brooklyn', 'https://www.blackforestbrooklyn.com','$30pp'),
(44, 'Sweet Catch', '1222 Nostrand Avenue', 'https://www.sweetcatchbk.com', 'Seafood', 'Casual Dining', 'Brooklyn', 'https://www.sweetcatchbk.com', '$50pp'),
(45, 'Jasmines Caribbean Cuisine', '371 W 46th St.', 'https://www.jasminecaribbeancuisine.com', 'Afro Caribbean','Casual Dining', 'Manhattan','https://www.jasminecaribbeancuisine.com', '$50pp'),
(46, 'Le Chai', '1904 Utica Ave', 'https://www.lechainyc.com', 'Asian', 'Casual Dining', 'Brooklyn', 'https://www.lechainyc.com', '$100pp'),
(47, 'Aliya', '500 Metropolitan Ave.', 'https://www.ihg.com/hotelindigo/hotels/us/en/brooklyn/nycmp/hoteldetail/dining/aliya', 'Caribbean Asian','Fine Dining', 'Manhattan', 'https://www.ihg.com/hotelindigo/hotels/us/en/brooklyn/nycmp/hoteldetail/dining/aliya','$50pp'),
(48, 'Taste of Heaven', '251 Jackson St.', 'http://www.tasteofheavenbk.com', 'Soul Food', 'Fast Casual', 'Brooklyn', 'http://www.tasteofheavenbk.com', '$10pp'),
(49, 'Clover Hill', '20 Columbia Pl.', 'https://www.cloverhillbk.com', 'New American', 'Fine Dining', 'Brooklyn', 'https://www.cloverhillbk.com', '$100pp'),
(50, 'Somethin On Myrtle', '503 Myrtle Ave.', 'https://www.somethinonmyrtle.com', 'Caribbean Asian', 'Casual Dining', 'Brooklyn','https://www.somethinonmyrtle.com', '$50pp'),
(51, 'The Row Harlem', '2374 Adam Clayton Powell Jr. Blvd.', 'https://therowharlem.com', 'American', 'Casual Dining', 'Manhattan', 'https://therowharlem.com', '$50pp'),
(52, 'The Grotto Bk', '321 Nostrand Ave.', 'https://thegrottobk.com', 'Afro Caribbean','Casual Dining', 'Brooklyn', 'https://thegrottobk.com', '$20pp');


INSERT INTO Therapists(id, name, certified, image_Url, bio, location, url) VALUES
(1, 'Kezzia Quintyne-Hilaire', 'LMHC, CASAC, Counselor', '', 'Your feelings are valid! As a Licensed Mental Health Counselor and a Black therapist in NYC, I understand the value of receiving quality therapy services. My practice is dedicated to helping women of color keep their crowns on straight. I specialize in trauma, womens issues, and anxiety. My primary therapeutic focus is Eye Movement Desensitization and Reprocessing (EMDR), which uses bilateral stimulation to help replace traumatic memories. Healing occurs through various approaches, so I also use multiple therapies to help my clients reduce depression, anxiety, work stress, and emotional distress.', 'Brooklyn','https://www.kqhcounseling.com/contact-black-female-therapist-nyc'),
(2, 'Keanu M. Jackson', 'Clinical Social Work/Therapist, LCSW', '', 'In our sessions, we will delve into the complex tapestry of your relationships, exploring the dynamics of intimacy and connection with honesty and vulnerability. From navigating communication challenges to deepening emotional intimacy, I provide practical tools and insightful guidance for you to foster healthier, more fulfilling connections with others and yourself. What excites me most about this work is being able to share space with those within my own communities. As a kinky, queer, Black therapist I recognize that what we need is the opportunity to expand our horizons in an effort to dive deeper into the richness of who we are.', 'Brooklyn', 'https://www.keanumjackson.com'),
(3, 'Queen Ravenden', 'Art Therapist, R-DMT, LCAT', '',	'Greetings and peace to you, divine being. I am a black, caribbean american, creative arts therapist providing safe, affirming, uplifting, and holistic healing. My therapeutic style uses a strength-based approach while incorporating creative art therapy techniques and catering to the balance & overall wellbeing of the mind, body, & soul. I work with individuals to overcome low self-esteem, self-doubt, anxiety, past traumas, and depression using creative arts therapy.', 'Brooklyn', 'https://www.mindbodysoulvirtualwellnesscenter.com'),
(4, 'Chelsea Thornton', 'Licensed Master Social Work, LMSW', '', 'I’m passionate in analyzing interpersonal connections through a multicultural lens. I frequently utilize CBT, EFT (Emotionally Focused Therapy), ARA (the Ackerman Relational Approach), and mindfulness techniques as we learn and embrace the many overlapping identities that exist within you. I provide services to children, teens, adults, couples, and families.', 'Brooklyn', 'https://www.zocdoc.com/professional/chelsea-thornton-lmsw-480442'),
(5, 'The Healing Collective', 'Clinical Social Work/Therapist, LCSW','', 'The Healing Collective is a New York-based therapeutic group practice that centers the healing of Black folks, Indigenous folks, and non-Black folks of color. We offer telehealth services to individuals (youth and adults), couples, and families throughout New York and New Jersey. We also offer coaching services throughout the United States. The Healing Collective believes that every being is worthy of healing and that our healing comes from within. We’d be honored if you chose us for your healing journey.', 'Brooklyn', 'https://www.thehealingcollectivepractice.com'),
(6, 'Shani Graves', 'Counselor, LMHC', '', 'Maybe its been two months or two years, but it has not been easy. Whether its your personal life, work life, familial, platonic, or romantic relationships. You may have begun to feel overwhelmed,annoyed, stressed, lonely and even depressed. You compare yourself to others and wonder why your life is not a reflection of the work you have put into it or how you imagined it would be. If any of these feelings have taken root in your life, contact me and my team today. Our role at SG Wellness is to create a space for Black, Latinx and People of Color to begin exploring patterns and work towards change. Together we can work to get you out of the haze, reduce pressure and set boundaries for yourself and others.', 'Brooklyn', 'https://sgcounselingnyc.com'),
(7, 'Tanner Kaleb Williams', 'Licensed Master Social Worker, LMSW', '', 'Hello there :) I am Tanner (he/him) a Black, queer, art and creativity lover based in Brooklyn, NY on occupied Lenape land. If you are searching for a therapist who truly listens and collaborates rather than just gives advice and diagnoses, I would be honored to connect with you. I focus on embracing radical acceptance, fostering community based care, and moving beyond labeling our experiences. If you are in need of a safe space to be your authentic self, we might be a perfect match. Please reach out! I am eager to hear about what is bringing you to therapy.', 'Manhattan', 'https://www.inclusivetherapists.com/new-york/brooklyn/tanner-williams'),
(8, 'Cloricea Brooks', 'Counselor, MA, LMHC, CASAC-T', '', 'Everyday we tell ourselves stories through our thoughts. These stories stem from our lived experiences, which are inseparable from our cultural identities. Life challenges like job stress, relationship issues, trauma, and grief can lead to stories that highlight fear, anger, mistrust, and sadness, resulting in detachment and difficulty feeling joy. I believe that restoring genuine connections with yourself and others is a powerful antidote. Together we will explore cognitive and behavioral interventions to change what you can, while intentionally accepting the unchangeable in a compassionate space.', 'Manhattan', 'https://headway.co/providers/cloricea-brooks'),
(9, 'Dr. Gary Dillon', 'Psychologist, PhD', '', 'Frustrated, stuck, or unfulfilled in an area of your life? You are not alone. Amid a global pandemic, along with the current social and political climate, knowing how to begin healing can be a challenge. Life is complicated and it can be difficult to reach out to gain the support and encouragement that you need to succeed. But don’t worry, I’ll be your ally on this journey - supporting and helping you along the way. As a Black male therapist in NYC, I specialize in working with individuals & couples, who at times feel powerless and are often marginalized - including immigrants, people of color, and members of the LGBTQIA+ community.', 'Manhattan', 'https://www.allypsychotherapy.com'),
(10, 'Racine Renee Henry', 'Marriage & Family Therapist, PhD, LMFT', '', 'The word Sankofa means "one must go back in order to move forward". The idea is that in order to move forward into our highest potential, we must use the best of what was in our past. As a relational therapist who primarily works from a Solution-Focused approach, the word Sankofa reflects my belief that learning from our experiences in the past can contribute to healing in the present and future. I believe we are all capable of change through an effective solution. I have experience bringing about the changes that will lead to a healthier and happier life. I specialize in treating couples from marginalized and minority groups. I have done extensive research and training on issues commonly experienced by women of all backgrounds, within the Black community and within Black romantic relationships.', 'Staten Island', 'https://www.sankofatherapynyc.com'),
(11, 'Amira R Martin', 'Clinical Social Work/Therapist, LCSW-R', '', 'I am here to provide you with warm and compassionate support as you navigate lifes challenges. Your journey is unique, and I want you to feel genuinely heard and understood. If you are facing issues like Depression, Anxiety, difficult relationships and work-related struggles, I am here to help you navigate and recover from these challenges. My commitment is to create a safe and supportive space for your healing. Together, we will address your struggles and challenges while fostering your personal growth and resilience. You can achieve emotional well-being, navigate life transitions, and ultimately lead a more fulfilling life.', 'Brooklyn', 'https://www.amiraforher.com'),
(12, 'Vanessa A. Williams', 'Counselor, LMHC', '', '"There is no greater agony than bearing the untold story inside you." - Maya Angelou. Each person’s story shapes them and a burden to carry alone that is relieved when met with empathy. I consider it an honor to be present with clients as they share their untold story, gain greater self-knowledge, and manifest the story that is yet to come. I come from a place of curiosity and non-judgement around each individual’s lived experience. I hope to create a warm, accepting space where you can be your authentic self, feel safe to express your uncensored thoughts and share both laughter and tears.', 'Brooklyn', 'https://rootsandbranchestherapy.nyc/vanessa-williams/'),
(13, 'Dwayne James', 'Clinical Social Work/Therapist, MSW, LCSW', '' ,'I say seeking therapy is nothing close to a sign of weakness but the biggest sign of strength you can possibly have. My name is Dwayne James, and I am a Black male clinician. With over five years of clinical therapeutic experience, my passion for social-emotional support continues to shine through with every client interaction. My overall therapeutic goal is to ensure folks get the essential tools to add to their tool kit in times of need while also providing the utmost support for their social and emotional needs. My work is rooted in cultural sensitivity and recognizes that clients are experts in their own experiences.', 'Brooklyn', 'https://headway.co/providers/dwayne-james?utm_source=pem&utm_medium=direct_link&utm_campaign=94657'),
(14, 'Uzoma Chibundu', 'Clinical Social Work/Therapist, LMSW', '','My therapeutic approach is collaborative, warm, authentic and holistic. I believe the client is the expert of their experiences and my purpose is to assist them in their journey toward healing. I help clients through an array of talk therapy, story telling and treatment-centered homework. I operate from a relational, intersectional, and anti-oppressive lens. Everyone has their own therapeutic journey, and who we bring on this journey is up to us. Ones journey towards healing can be a culmination of tough conversations, laughter, and tears. My hope is that we all find people to accompany us on our therapeutic journey. Lets schedule a free consultation to see we would be a good fit.', 'Brooklyn', 'https://www.psychologytoday.com/us/therapists/uzoma-chibundu-brooklyn-ny/1051407');
