INSERT INTO Galleries(id, name, address, image_Url, founder, location, url) VALUES
(1, 'Richard Beavers Gallery', '14 Wooster Street', 'www.richardbeaversgallery.com', 'Richard Beavers', 'Manhattan', 'www.richardbeaversgallery.com'),
(2, 'MoCADA', '80 Hanson Pl','www.MoCada.com','Laurie Angela Cumbo', 'Brooklyn','www.MoCada.com'),
(3, 'Bedford Stuyvesant Museum of African Art', '1157 Bedford Ave', 'www.bsma.com','Eric Edwards', 'Brooklyn', 'www.bsma.com'),
(4, 'Bishop Gallery', '630 Flushing Ave', 'www.bishopgallery.com', 'Erwin John & Stevenson Dunn Jr.', 'Brooklyn', 'www.bishopgallery.com'),
(5, 'The Studio Museum', '429 West 127th St', 'www.studiomuseum.com', 'Charles Inniss','Manhattan', 'www.studiomuseum.com'),
(6, 'Nicola Vassell Gallery', '138 10th Avenue', 'www.vassellgallery.com','Nicola Vassell', 'Brooklyn','www.vassellgallery.com'),
(7, 'Heath Gallery', '24 W 120th St','www.heathgallery.com', 'Thomas Edwin & Saundra Alexis Heath', 'Manhattan', 'www.heathgallery.com'),
(8, 'Long Gallery', '2073 Adam Clayton Powell Jr Blvd', 'www.longgallery.com', 'Lewis Long', 'Manhattan','www.longgallery'),
(9, 'Hannah Traore Gallery', '150 Orchard Street', 'www.hannahtraoregallery.com', 'Hannah Traore', 'Manhattan','www.hannahtraoregallery'),
(10, 'Welancora Gallery', '33 Herkimer Street', 'www.welancoragallery.com','Ivy N. Jones', 'Brooklyn', 'www.welancoragallery.com'),
(11, 'Dorsey Art Gallery', '553 Rogers Ave.','www.dorseyartgallery.com','Lawrence P. Dorsey', 'Brooklyn','www.dorseyartgallery.com'),
(12, 'Ground Gallery', '80 Richards St.', 'www.groundgallery.com','Krista Scenna & Jill Benson', 'Brooklyn', 'www.groundgallery.com'),
(13, 'Medium Tings', '1134 President Street', 'www.mediumtings.com', 'Stephanie Baptist','Brooklyn', 'www.mediumtings.com'),
(14, 'Jenkins Johnson Gallery', '207 Ocean Ave.', 'www.jenkinsjohnsongallery.com', 'Karen Jenkins Johnson','Brooklyn', 'www.jenkinsjohnsongallery.com'),
(15, 'Housing Gallery', '191 Henry St.', 'www.housinggallery.com', 'KJ Freeman & Eileen Skyers','Manhattan','www.housinggallery.com'),
(16, 'Essie Green Gallery', '4213,419 Convent Ave. A','www.essiegreengallery.com','Essie Green & Sherman Edmiston', 'Manhattan', 'www.essiegreengallery.com'),
(17, 'Black Gotham Experience', '192 Front St.', 'www.blackgotham.com', 'Kamau Ware', 'Manhattan','www.blackgotham.com'),
(18, 'Cindy Rucker Gallery', '143 Orchard Street', 'www.cindyruckergallery.com', 'Cindy Rucker', 'Manhattan','www.cindyruckergallery.com'),
(19, 'Peg Alston Fine Arts', '407 Central Park W Apt. K', 'www.pegalstonfinearts.com', 'Peg Alston', 'Manhattan', 'www.pegalstonfinearts.com'),
(20, 'Skoto Gallery', '529 W20th St., #5FL','www.skotogallery.com', 'Skoto Aghahowa', 'Brooklyn','www.skotogallery.com'),
(21, 'Mackey Twins Art Gallery', '457 E. Sidney Ave.', 'www.mackeytwinsartgallery.com', 'Karen & Sharon Mackey', 'Brooklyn', 'www.mackeytwinsartgallery.com'),
(22, 'June Kelly Gallery', '166 Mercer St. #3C', 'www.junekellygallery.com', 'June Kelly', 'Brooklyn', 'www.junekellygallery.com'),
(23, 'The Compound', '185 Van Dyke St.', 'www.compound7.series', 'Free Richardson', 'Manhattan', 'www.compound7.series'),
(24, 'Cierra Britton Gallery', '220b Plymouth St.', 'www.cierrabritton.com', 'Cierra Britton', 'Brooklyn','www.cierrabritton.com'),
(25, 'Black Wall Street Gallery', '14 Wooster St.','www.bwsgallery.com', 'Ricco Wright', 'Manhattan', 'www.bwsgaler.com'),
(26, 'Tanya Weddemire Gallery', '254 36th Street, STE C257', 'www.tanyaweddemiregallery.org', 'Tanya Weddemire', 'Manhattan','www.tanyaweddemiregallery.org'),
(27, 'Calabar Gallery', '306 W 38th St.', 'www.calabargallery.com', 'Atim Annette Oton', 'Manhattan','www.calabargallery.com'),
(28, 'Bill Hodges Gallery', '521 W 20th St., #10E','www.billhodgesgallery.com', 'Bill Hodges', 'Manhattan', 'www.billhodgesgallery.com'),
(29, 'Curtiss Jacobs Gallery', '2075 Adam Clayton Powell Jr Blvd', 'www.curtissjacobsgallery.com', 'Curtiss Jacobs', 'Manhattan','www.curtissjacobsgallery.com'),
(30, 'Kente Royal Gallery', '2373 Adam Clayton Powell Jr Blvd', 'www.kenteroyalgallery.com', 'Phyllis & Dodji Gbedemah', 'Manhattan','www.kenteroyalgallery.com');

INSERT INTO Cafes(id, name, address, location, image_Url, beverage, url) VALUES
(1, 'Che', '302 Malcolm X Blvd.', 'Manhattan', 'www.che.com', 'Cafe', 'www.che.com'),
(2, 'I Like It Black', '409 W 125th St.', 'Manhattan', 'www.ilikeitblack', 'Cafe', 'www.ilikeitblack'),
(3, 'Buuni Cafe', '213 Pinehurst Ave.', 'Manhattan', 'www.buunicafe.com', 'Cafe', 'www.buunicafe.com'),
(4, 'Hibiscus Brew', '546 Flatbush Ave.','Brooklyn', 'www.hibiscusbrew.com', 'Cafe', 'www.hibiscusbrew.com'),
(5, 'Aunts Et Uncles', '1407 Nostrand Ave.', 'Brooklyn', 'www.auntsetuncles.com', 'Cafe', 'www.auntsetuncles.com'),
(6, 'Bklyn Blend', '194 Tompkins Ave.', 'Brooklyn', 'www.blklynblend.com', 'Cafe', 'www.blklynblend.com'),
(7, 'Bushwick Grind', '63 Whipple St.', 'Brooklyn', 'www.bushwickgrind.com', 'Cafe', 'www.bushwickgrind.com'),
(8, 'Brown Butter Craft Bar & Kitchen', '413 Thompkins Ave.', 'Brooklyn', 'www.brownbutternyc.com', 'Cafe', 'www.brownbutternyc.com'),
(9, 'St. Michel Cafe', '462 Irving Ave.', 'Brooklyn', 'www.michelcafe.com', 'Cafe', 'www.michelcafe.com'),
(10, 'Milk & Pull', '778 Seneca Ave.', 'Brooklyn', 'www.milkandpull.com', 'Cafe', 'www.milkandpull.com'),
(11, 'Lakou cafe', '195 Utica Ave.', 'Brooklyn', 'www.lakoucafe.com', 'Cafe', 'www.lakoucafe.com'),
(12, 'Sweet Sundays Cafe', '2916 Beverley Rd.', 'Brooklyn', 'www.sweetsunday.com', 'Cafe','www.sweetsunday.com'),
(13, 'Boogie Down Grind', '88 Hunts Point', 'Bronx', 'www.boogiedowngrind.com', 'Cafe', 'www.che.com'),
(14, 'Ginjan Cafe', '85 E 125th St.', 'Manhattan', 'www.ilikeitblack', 'Cafe', 'www.ilikeitblack'),
(15, 'The Oma, Shop', '1707 Amsterdam Ave.', 'Manhattan', 'www.buunicafe.com', 'Cafe', 'www.buunicafe.com'),
(16, 'LoveLane BK', '674 Nostrand Ave.', 'Brooklyn', 'www.hibiscusbrew.com', 'Cafe', 'www.hibiscusbrew.com'),
(17, 'Coffee Uplifts People', '329 Gates Ave.', 'Brooklyn', 'www.auntsetuncles.com', 'Cafe', 'www.auntsetuncles.com'),
(18, 'Chez Alex', '72 Ralph Ave.',  'Brooklyn', 'www.blklynblend.com', 'Cafe', 'www.blklynblend.com'),
(19, 'Zaca Cafe', '429 Marcus Garvey Blvd.', 'Brooklyn', 'www.bushwickgrind.com', 'Cafe', 'www.bushwickgrind.com'),
(20, 'Greenhouse Cafe @ Seed Brklyn', '1217 Bedford Ave.', 'Brooklyn', 'www.brownbutternyc.com', 'Cafe', 'www.brownbutternyc.com'),
(21, 'Brooklyn Perk', '605 Flatbush Ave.', 'Brooklyn', 'www.michelcafe.com', 'Cafe', 'www.michelcafe.com'),
(22, 'NBHD Brulee', '2620 Frederick Douglass Blvd.', 'Manhattan', 'www.milkandpull.com', 'Cafe', 'www.milkandpull.com'),
(23, 'Nurish', '637A Vanderbilt Ave.', 'Brooklyn', 'www.lakoucafe.com', 'Cafe', 'www.lakoucafe.com'),
(24, 'Deja Brew Cafe', '102- 10 Jamaica Ave.', 'Queens', 'www.sweetsunday.com', 'Cafe','www.sweetsunday.com'),
(25, 'Lips Cafe', '1412 Nostrand Ave.', 'Brooklyn', 'www.che.com', 'Cafe', 'www.che.com'),
(26, 'September', '83 Saratoga Ave.', 'Brooklyn', 'www.ilikeitblack', 'Cafe', 'www.ilikeitblack'),
(27, 'Cups and Books', '2024 Bedford Ave.', 'Brooklyn', 'www.buunicafe.com', 'Cafe', 'www.buunicafe.com'),
(28, 'Miss Barbs', '1038 Nostrand Ave.', 'Brooklyn', 'www.hibiscusbrew.com', 'Cafe', 'www.hibiscusbrew.com'),
(29, 'Brooklyn Tea', '411 Lewis Ave.', 'Brooklyn', 'www.auntsetuncles.com', 'Cafe', 'www.auntsetuncles.com'),
(30, 'Cafe Lakay', '3323 Avenue I',  'Brooklyn', 'www.blklynblend.com', 'Cafe', 'www.blklynblend.com');

INSERT INTO JuiceBars(id, name, address, location, image_Url, beverage, url) VALUES
(1, 'Bkln Blend', '194 Tompkins Ave', 'Brooklyn', 'www.blklynblend.com', 'Juice Bar', 'www.blklynblend.com'),
(2, 'The Juice Gallery', '1647 Bedford Ave.', 'Brooklyn', '', 'Juice Bar', ''),
(3, 'Passa Passa', '401 Rogers Ave.', 'Brooklyn', '', 'Juice Bar', ''),
(4, 'Unks Place', '1962 Madison Ave.', 'Manhattan', '', 'Juice Bar', ''),
(5, 'Juice Worx', '90 St. Nicholas', 'Manhattan', '', 'Juice Bar', ''),
(6, 'Cocoa Bean Juice & Salad Bar', '1510 Nostrand Ave.', 'Brooklyn', '', 'Juice Bar', ''),
(7, 'Canarsie Blend Juice Bar', '9202 Avenue M', 'Brooklyn', '', 'Juice Bar', ''),
(8, 'Mad Juicy', '100 W 139th St.', 'Manhattan', '', 'Juice Bar', ''),
(9, 'Juice Joint', '144-14 ROckaway Blvd.', 'Queens', '', 'Juice Bar', ''),
(10, 'Les Deux Nutrition Juice', '662 Blake Ave.', 'Brooklyn', '', 'Juice Bar', ''),
(11, 'Uptown Juice Bar', '2524 Adam Clayton Powell Jr. Blvd.', 'Manhattan', '', 'Juice Bar', ''),
(12, 'Green Garden Health Food', '3543 White Plains Rd.', 'Bronx', '', 'Juice Bar', '');
